version: '3'

# Before:
# 'docker pull cassandra' (install docker)
# 'gradle jibDockerBuild' at project directory

services:
  cassandra:
    container_name: webflux-cassandra
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    restart: always
    volumes:
      - ./cassandra_data:/var/lib/cassandra
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:latest
    depends_on:
      - cassandra
    volumes:
      - ./data_schema.cql:/schema.cql
    command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"